[manifest] # this is required for your lovely patches to work
version = "1.0.0"
dump_lua = true
priority = 0

# initiate variables
[[patches]]
[patches.pattern] # this is a simple pattern patch you can make to initiate a global variable
target = "game.lua" # the target file you will patch the payload into
pattern = "rental_rate = 3," # the pattern to search for in the target file
position = "after" # this will put the payload after the pattern
payload = '''
exmp_example_variable = 0,
storage = 0, -- this is for a custom resource/variable that can be found in the Utility.lua of the example mod
''' # this is what will be patched into the target file
match_indent = true

# use Storage button
[[patches]]
[patches.pattern] # this is a simple pattern patch you can make to initiate a global variable
target = "functions/UI_definitions.lua" # the target file you will patch the payload into
pattern = "function G.UIDEF.use_and_sell_buttons(card)" # the pattern to search for in the target file
position = "after" # this will put the payload after the pattern
payload = '''
    local exmp_rsc = nil
    if card.area and card.area.config.type == 'joker' and card.ability.set == 'Joker' then -- checks if the card is a joker
        if card.ability.exmp_storage == true then -- checks if the joker has the storage ability
            -- the code below is what we use to create our use storage button
            exmp_rsc = 
            {n=G.UIT.C, config={align = "cl"}, nodes={
            
                {n=G.UIT.C, 
                config={ref_table = card, align = "cl",maxw = 1.25, padding = 0.1, r=0.08, minw = 1.0, hover = true, shadow = true, colour = G.C.GOLD, one_press = true, button = 'use_storage', func = 'can_use_storage'}, 
                nodes={
                {n=G.UIT.B, config = {w=0.1,h=0.6}},
                {n=G.UIT.C, config={align = "tm"}, 
                nodes={
                    {n=G.UIT.R, config={align = "cm", maxw = 1.25}, 
                    nodes={
                        {n=G.UIT.T, config={text = localize('b_use'),colour = G.C.UI.TEXT_LIGHT, scale = 0.4, shadow = true}}
                    }},
                    {n=G.UIT.R, config={align = "cm"}, 
                    nodes={
                        {n=G.UIT.T, config={text = "Storage",colour = G.C.WHITE, scale = 0.55, shadow = true}}
                    }}
                }}
                }}
            }}
        end
    end

'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = 'cl'}, nodes={
            use
          }},'''
position = "after"
payload = '''
{n=G.UIT.R, config={align = 'cl'}, nodes={
            exmp_rsc
          }},
'''
match_indent = true